title: Guoweixin's Homepage
page-top-title: Guo Weixin
top-section-bg-text: Be what you wanna be
home-subtitle: Guo&ensp;Weixin&ensp;|&ensp;郭维欣
copyright-text: '&copy; Guo Weixin 2025-2025. All Rights Reserved.'
